# -*- coding: utf-8 -*-
"""Tám chương trình trong hệ sinh thái Next Gen Founder.
Nguồn: NGF-05 v1.2, NGF-17 v2.2 và tài liệu TFB-01 v6.1. Không tự thêm chương trình mới."""

CT = [

dict(tep="trusted-founder-brand.html", nhom="Bốn năng lực",
 ten="Trusted Founder Brand Challenge",
 ten_vi="Thử thách ba tuần xây thương hiệu nhà sáng lập được tin cậy",
 nang_luc="Năng lực 01 · Thương hiệu nhà sáng lập được tin cậy",
 tom="Làm rõ bạn phục vụ ai, giải vấn đề gì và có cách làm gì riêng, rồi đưa định vị đó ra thị trường bằng tiếng nói, câu chuyện và nội dung của chính bạn.",
 anh="img/cd-giang-slide.webp", alt="Coach Duy Nguyễn giảng trước màn chiếu",
 mo_ban=True,
 dieu_kien=['Đã có sản phẩm, khách hàng và kinh nghiệm thật, không phải đang trong giai đoạn tìm hướng',
            'Chuyên môn hoặc uy tín cá nhân của bạn ảnh hưởng trực tiếp tới việc khách tin và chọn doanh nghiệp',
            'Dành được khoảng ba tới bốn giờ mỗi tuần trong ba tuần cho phần thực hành',
            'Đăng ký được ngay, khoá đầu tiên khai giảng ngày 28 tháng 9 năm 2026'],
 cho_ai="Nhà sáng lập, chủ doanh nghiệp và chuyên gia đã có sản phẩm, khách hàng và kinh nghiệm thật, nhưng nội dung chưa cho thấy hết năng lực hoặc cứ dừng lại khi công việc bận lên. Người làm bán hàng chỉ nên tham gia khi đang đi lên vai trò chuyên gia, cố vấn hoặc người chủ.",
 luan_diem="Không ai xây được thương hiệu cá nhân bằng số lượng bài đăng. Nó lớn dần khi đúng người liên tục nhận ra cùng một chuyên môn, cùng một tiêu chuẩn và cùng một cách nhìn qua những bằng chứng thật.",
 ket_qua=["Có một bản định vị phiên bản đầu: khách hàng trọng tâm, vấn đề ưu tiên, đề nghị chính, cách giải quyết riêng và bằng chứng đang có",
          "Tìm ra tiếng nói và cách xuất hiện đáng tin theo điểm mạnh của chính bạn, không bắt chước ai",
          "Gom được chất liệu và câu chuyện từ công việc thật, dùng được lâu dài thay vì cạn ý sau vài tuần",
          "Làm ra những nội dung đầu tiên đúng với con người thật, đưa định vị ra cho khách nhìn thấy",
          "Có nhịp làm việc để tiếp tục, không phải ngày nào cũng tự hỏi hôm nay đăng gì"],
 hinh_thuc="Ba tuần, hoàn thành theo bài thực hành chứ không phải làm liên tục 21 ngày. Cần khoảng ba tới bốn giờ mỗi tuần. Trong ba tuần có 15 lần điểm danh thực hành, đi đủ 12 lần thì nhận quà.",
 khai_giang="Khoá đầu tiên khai giảng ngày 28 tháng 9 năm 2026",
 khong_gom=["Không bảo đảm số lượt xem, người theo dõi, khách hàng hoặc doanh thu",
            "Không hứa sau ba tuần bạn nổi tiếng hoặc có ngay khách hàng tìm đến",
            "Không tái cấu trúc toàn bộ thương hiệu doanh nghiệp, chỉ là bản định vị phiên bản đầu",
            "Không gồm quà tặng thu thông tin, chuỗi chăm sóc và hệ thống bán hàng hoàn chỉnh",
            "Không làm nội dung thay bạn"]),


dict(tep="trusted-sales-team-system.html", nhom="Bốn năng lực",
 ten="Trusted Sales Team System",
 ten_vi="Xây dựng Đội ngũ Tư vấn Bán hàng Chuyên nghiệp và Tin cậy",
 nang_luc="Năng lực 02 · Chuyên gia tư vấn được tin cậy",
 tom="Trong hai ngày học tập trung và khoảng ba mươi ngày hoàn thiện, nhà sáng lập xây Bản thiết kế Hệ thống Phòng Kinh doanh phiên bản 1 cho chính doanh nghiệp mình.",
 anh="img/cd-dung-lop.webp", alt="Coach Duy Nguyễn đứng lớp trước một đội ngũ",
 dieu_kien=['Đội ngũ bán hàng từ ba người trở lên',
            'Sản phẩm hoặc dịch vụ của bạn cần tư vấn và cân nhắc trước khi khách quyết định',
            'Nhà sáng lập tham gia đủ hai ngày học tập trung và phiên chốt bản thiết kế',
            'Doanh nghiệp đang thiếu quy trình, tiêu chuẩn, cách đánh giá hoặc cách rà soát',
            'Sẵn sàng dành thời gian xây bản thiết kế và chịu trách nhiệm triển khai sau đó'],
 cho_ai="Nhà sáng lập đang xây hoặc đang sửa phòng kinh doanh. Nhà sáng lập là người mua và người phê duyệt, quản lý bán hàng được khuyến nghị mạnh nhưng không bắt buộc, nhân sự tham gia theo gói quyền lợi của doanh nghiệp. Người chưa có đội ngũ vẫn tham gia được, nhưng chỉ cầm về một bản thiết kế để chuẩn bị chứ chưa phải hệ thống đã kiểm chứng. Chưa hợp với thương mại điện tử và bán lẻ giao dịch nhanh.",
 luan_diem="Vấn đề không nằm ở kỹ năng của từng người. Phòng kinh doanh đang thiếu một hệ thống nối được định vị, hành vi, quy trình, dữ liệu và cách quản lý, nên càng đông khách thì người chủ càng phải quay lại ngồi bán thay đội ngũ.",
 ket_qua=["Bản thiết kế Hệ thống Phòng Kinh doanh phiên bản 1, gồm bảy cấu phần",
          "Tuyên bố định vị và nguyên tắc của đội ngũ bán hàng",
          "Bản đồ mục tiêu và quy trình từ tiếp nhận cơ hội đủ điều kiện đến bàn giao",
          "Bộ chuẩn tư vấn và hành vi theo The Trusted Advisor, kèm bản đồ vai trò và trách nhiệm",
          "Bộ Canvas, biểu mẫu, dữ liệu, chỉ số và kế hoạch hành động tiếp theo"],
 hinh_thuc="Ba giai đoạn. Phần học nền về The Trusted Advisor cùng bản tự đánh giá tình trạng phòng kinh doanh. Hai ngày học tập trung để tạo bản đầu của cả bảy cấu phần. Khoảng ba mươi ngày hoàn thiện bằng Canvas, biểu mẫu và AI, rồi nộp một bản thiết kế cuối để được chấm theo bốn mức.",
 khong_gom=["Không triển khai hệ thống thay doanh nghiệp, phần đó thuộc một hợp đồng riêng",
            "Không quyết định thay và không thẩm định pháp lý cho chính sách vai trò, chỉ tiêu, tuyển dụng hoặc lương thưởng",
            "Không nhận luồng tăng trưởng xuyên phòng ban, phần đó thuộc Founder Growth System",
            "Không thay đổi toàn bộ văn hóa doanh nghiệp",
            "Không cam kết doanh số hoặc tỷ lệ chuyển đổi",
            "Không cấp chứng nhận năng lực Cố vấn Tin cậy cho từng cá nhân"]),


dict(tep="founder-growth-system.html", nhom="Bốn năng lực",
 ten="Founder Growth System", ten_vi="Hệ thống tăng trưởng cùng đội ngũ",
 nang_luc="Năng lực 03 · Xây hệ thống cùng đội ngũ",
 tom="Đưa một luồng công việc quan trọng ra khỏi đầu người chủ: kết quả rõ, người chịu trách nhiệm rõ, và một nhịp rà soát dựa trên dữ liệu.",
 anh="img/cd-dung-lop.webp", alt="Coach Duy Nguyễn nói trước một phòng người sáng lập",
 dieu_kien=['Đã có sản phẩm, khách hàng và một đội ngũ nòng cốt đang chạy',
            'Có quản lý chủ chốt tham gia được một số phiên, không để người chủ đi học một mình',
            'Chấp nhận đưa số liệu vận hành thật ra bàn',
            'Mở khi phạm vi phù hợp, bắt đầu bằng một buổi trao đổi ngắn'],
 cho_ai="Nhà sáng lập đã có sản phẩm, khách hàng và đội ngũ nòng cốt, nhưng tăng trưởng và vận hành còn phụ thuộc vào mình.",
 luan_diem="Kết quả không thể chỉ nằm trong trí nhớ và sự đôn đốc của người chủ. Một hệ thống phải có kết quả rõ, người chịu trách nhiệm, tiêu chuẩn, dữ liệu, bàn giao và nhịp cải tiến.",
 ket_qua=["Một luồng thu hút, tư vấn, bán hàng hoặc vận hành có kết quả rõ ràng",
          "Một người chịu trách nhiệm cho luồng đó, không phải một phòng ban",
          "Dữ liệu đủ để biết luồng đang khoẻ hay yếu, và một nhịp rà soát cố định",
          "Bản đồ Trust Orbit và hệ sinh thái sản phẩm của riêng doanh nghiệp bạn",
          "Kế hoạch triển khai 90 ngày cùng đội ngũ"],
 hinh_thuc="4 đến 6 buổi trực tuyến, gồm một số phiên chọn lọc cho quản lý chủ chốt.",
 khong_gom=["Không viết hộ quy trình cho toàn bộ doanh nghiệp",
            "Không nhận vai điều hành thay người chủ",
            "Không cam kết một con số doanh thu"]),

dict(tep="community-growth-system.html", nhom="Bốn năng lực",
 ten="Community Growth System", ten_vi="Hệ thống tăng trưởng từ cộng đồng",
 nang_luc="Năng lực 04 · Kiến tạo cộng đồng",
 tom="Thiết kế một cộng đồng mà giá trị do thành viên tạo cho nhau, không chỉ chảy một chiều từ người sáng lập xuống.",
 anh="img/ngf-nu-2.webp", alt="Ảnh minh hoạ một nhà sáng lập",
 dieu_kien=['Đã có khách hàng, học viên hoặc người theo dõi, tức đã có người để tập hợp',
            'Có người phụ trách cộng đồng tham gia cùng, không giao lại cho một người làm nội dung',
            'Sẵn sàng chạy thử một nhịp cộng đồng thật ngay trong thời gian học',
            'Mở khi phạm vi phù hợp, bắt đầu bằng một buổi trao đổi ngắn'],
 cho_ai="Nhà sáng lập đã có khách hàng, học viên hoặc người theo dõi, nhưng quan hệ thường kết thúc sau giao dịch và mọi giá trị vẫn phụ thuộc vào mình.",
 luan_diem="Cộng đồng không phải nhóm đăng bài hoặc nơi chào hàng. Giá trị phải được tạo giữa các thành viên qua thực hành, phản hồi, kết nối, giới thiệu và hợp tác có chọn lọc.",
 ket_qua=["Lời hứa cộng đồng rõ ràng và tiêu chuẩn thành viên",
          "Trải nghiệm mười bốn ngày đầu để người mới có kết quả nhỏ sớm",
          "Nghi thức và nhịp hoạt động để mọi người biết khi nào quay lại",
          "Cơ chế tạo quan hệ, giữ chân, giới thiệu và cơ hội kinh doanh giữa thành viên",
          "Chạy thử một nhịp cộng đồng thật ngay trong chương trình"],
 hinh_thuc="4 đến 6 buổi trực tuyến, kết hợp thiết kế và chạy thử một nhịp cộng đồng thật, gồm một số phiên cho người phụ trách cộng đồng.",
 khong_gom=["Không vận hành cộng đồng thay bạn",
            "Không bảo đảm số thành viên",
            "Không hợp với người chỉ muốn có thêm một nhóm để bán hàng"]),

dict(tep="cong-dong-thanh-vien.html", nhom="Đồng hành",
 ten="Cộng đồng Thành viên Next Gen Founder", ten_vi="Luyện đủ bốn năng lực suốt một năm",
 nang_luc="Sản phẩm chủ đạo",
 tom="Không phải một gói xem nội dung không giới hạn. Là môi trường phát triển theo một lộ trình có nhịp, ở đó bạn được phản hồi và có người đi cùng.",
 anh="img/cd-san-khau.webp", alt="Coach Duy Nguyễn trên sân khấu",
 la_cong_dong=True,
 dieu_kien=['Là founder hoặc chủ doanh nghiệp mà uy tín cá nhân ảnh hưởng tới việc khách chọn; nếu là chuyên gia, đã có sản phẩm, khách hàng, doanh thu và ý định xây hệ thống vượt khỏi số giờ cá nhân',
            'Muốn luyện đủ bốn năng lực trong công việc thật, không tìm một kho nội dung để xem',
            'Cam kết theo năm và đi được nhịp hoạt động cố định hằng tháng',
            'Bắt đầu bằng trải nghiệm mười bốn ngày đầu'],
 cho_ai="Founder hoặc chủ doanh nghiệp mà uy tín cá nhân ảnh hưởng tới việc khách chọn, muốn phát triển bốn năng lực trong công việc thật; gồm chuyên gia đang xây doanh nghiệp từ chuyên môn.",
 luan_diem="Khoá học là lộ trình năng lực bên trong hành trình thành viên, không phải trung tâm của mô hình. Giá trị được đo bằng thay đổi có bằng chứng, không bằng số giờ video đã xem.",
 ket_qua=["Lộ trình bốn năng lực, đi theo điểm nghẽn của bạn chứ không theo thứ tự cứng",
          "Thư viện chương trình và công cụ dùng được trong việc thật",
          "Phiên thực hành và phản hồi trên tình huống của chính bạn",
          "Nhóm đồng hành và kết nối giữa các thành viên",
          "Hồ sơ tiến bộ ghi lại Bước Tăng Trưởng có bằng chứng"],
 hinh_thuc="Thành viên theo năm, có nhịp hoạt động cố định hằng tháng và trải nghiệm mười bốn ngày đầu để bắt đầu đúng.",
 khong_gom=["Không gồm tư vấn riêng không giới hạn",
            "Không gồm quyền tiếp cận Coach Duy bất cứ lúc nào",
            "Không gồm triển khai hệ thống cho doanh nghiệp",
            "Không cam kết doanh thu"]),

dict(tep="diamond-founder-club.html", nhom="Đồng hành",
 ten="Diamond Founder Club", ten_vi="Cộng đồng đồng hành cao cấp, theo lời mời",
 nang_luc="Tầng cao cấp",
 tom="Dành cho nhà sáng lập đã có kết quả, có tinh thần đóng góp và phù hợp văn hoá. Nhận qua xét mời, không mở đăng ký.",
 anh="img/ngf-nam-4.webp", alt="Ảnh minh hoạ một nhà sáng lập",
 dieu_kien=['Thuộc đúng nhóm khách hàng lõi của Next Gen Founder',
            'Đã có kết quả quan sát được, không chỉ có kế hoạch',
            'Có tinh thần đóng góp cho người đi sau và phù hợp văn hoá cộng đồng',
            'Nhận qua xét mời của hội đồng, không mở đăng ký công khai'],
 cho_ai="Nhà sáng lập đúng nhóm khách hàng lõi, đã có kết quả quan sát được, có tinh thần đóng góp cho người đi sau và phù hợp văn hoá.",
 luan_diem="Khả năng chi trả là điều kiện cần, không phải điều kiện đủ. Một cộng đồng cao cấp giữ được chất lượng bằng cách chọn người, không bằng cách chọn giá.",
 ket_qua=["Founder Council, nơi các quyết định lớn được đưa ra bàn cùng người ngang tầm",
          "Bốn lộ trình năng lực ở mức chuyên sâu",
          "Business Clinic cho tình huống thật của doanh nghiệp thành viên",
          "Quyền tham gia chọn lọc cho quản lý chủ chốt",
          "Mạng lưới nhà sáng lập, hoạt động đời sống và cơ chế ghi nhận"],
 hinh_thuc="Xét mời qua hội đồng. Thành viên theo năm.",
 khong_gom=["Không gồm triển khai hệ thống cho doanh nghiệp",
            "Không gồm tư vấn riêng không giới hạn",
            "Không nhận vai làm thuê chức năng",
            "Không cam kết doanh thu",
            "Không gồm quyền tiếp cận Coach Duy bất cứ lúc nào"]),

dict(tep="co-van-rieng.html", nhom="Riêng",
 ten="Founder Private&nbsp;Advisory", ten_vi="Cố vấn riêng cho nhà sáng lập",
 nang_luc="Một kèm một",
 tom="Bốn tháng đi cùng một nhà sáng lập đang đứng trước một quyết định chiến lược đủ lớn. Công suất rất giới hạn.",
 anh="img/cd-cat-soc.webp", alt="Chân dung Coach Duy Nguyễn", anh_tach_nen=True,
 dieu_kien=['Đang đứng trước một quyết định chiến lược đủ lớn để đáng bàn trong bốn tháng',
            'Sẵn sàng đưa quyết định đó ra bàn với một người ngoài doanh nghiệp',
            'Cam kết đi hết bốn tháng, không dừng giữa chừng khi việc bận lên',
            'Công suất rất giới hạn, Duy nhận chọn lọc và có thể từ chối'],
 cho_ai="Số ít nhà sáng lập có quyết định chiến lược đủ lớn, và đã sẵn sàng đưa quyết định đó ra bàn với một người ngoài.",
 luan_diem="Cố vấn riêng không phải là gói cao nhất trong một chiếc thang giá. Nó là một phạm vi riêng, chỉ hợp khi quyết định đủ lớn để xứng đáng với thời gian của cả hai bên.",
 ket_qua=["Gọi đúng tên quyết định đang phải ra, và điều kiện để ra được quyết định đó",
          "Một bản đồ lựa chọn với cái giá của từng lựa chọn",
          "Nhịp làm việc cố định trong bốn tháng để bám theo tiến độ thật",
          "Tiêu chí để bạn tự đánh giá những quyết định tương tự về sau"],
 hinh_thuc="Cố vấn một kèm một trong bốn tháng. Nhận chọn lọc, không đặt mục tiêu bán số lượng.",
 khong_gom=["Không làm thay phần việc điều hành",
            "Không nhận nếu quyết định chưa đủ lớn để cần cố vấn riêng",
            "Không cam kết doanh thu"]),

dict(tep="giai-phap-doanh-nghiep.html", nhom="Riêng",
 ten="90 Ngày Xây Hệ thống Tăng&nbsp;trưởng", ten_vi="Giải pháp cho doanh nghiệp",
 nang_luc="Hợp đồng doanh nghiệp",
 tom="Chẩn đoán, thiết kế, xây, chạy thử và bàn giao một hệ thống tăng trưởng có người phụ trách, dữ liệu và nhịp điều hành.",
 anh="img/ngf-nam-2.webp", alt="Ảnh minh hoạ một nhà sáng lập",
 dieu_kien=['Nhà sáng lập và quản lý chủ chốt cùng tham gia, không uỷ quyền hoàn toàn cho cấp dưới',
            'Có dữ liệu vận hành để đọc, dù chưa gọn',
            'Có một vấn đề lặp lại đủ rõ để đặt làm phạm vi',
            'Cam kết 90 ngày, gồm cả phần chạy thử và bàn giao'],
 cho_ai="Doanh nghiệp có nhà sáng lập và quản lý chủ chốt cùng tham gia, có dữ liệu và có vấn đề lặp lại đủ rõ.",
 luan_diem="Giải pháp doanh nghiệp chỉ mở rộng khi đã có bằng chứng, có công suất và có người chịu trách nhiệm giao hàng. Vì vậy số lượng nhận mỗi đợt rất ít.",
 ket_qua=["Chẩn đoán điểm nghẽn ở mức doanh nghiệp, không chỉ ở mức người chủ",
          "Thiết kế và xây một hệ thống tăng trưởng cho một luồng ưu tiên",
          "Chạy thử trong việc thật, có dữ liệu và tài liệu",
          "Bàn giao cho người phụ trách trong doanh nghiệp, kèm nhịp điều hành"],
 hinh_thuc="90 ngày. Phạm vi có thể gồm Trust Orbit, hệ sinh thái sản phẩm, hệ thống quản lý khách hàng, hội thảo, tư vấn bán hàng, bảng chỉ số và tài liệu vận hành.",
 khong_gom=["Không nằm trong phí Cộng đồng Thành viên hoặc Diamond, đây là hợp đồng riêng",
            "Không bán đại trà, mỗi đợt nhận rất ít doanh nghiệp",
            "Không nhận nếu quản lý chủ chốt không tham gia",
            "Không cam kết doanh thu"]),

dict(tep="cong-dong-mo.html", nhom="Đồng hành",
 ten="Cộng đồng Mở Next Gen Founder", ten_vi="Cửa vào rộng nhất, không mất phí nhưng có sàng lọc",
 nang_luc="Cửa vào",
 tom="Chỗ để bạn tìm hiểu nhân dạng Next Gen Founder trước khi quyết định đi sâu, bằng nội dung chọn lọc và công cụ tự đánh giá.",
 anh="img/cd-san-khau.webp", alt="Coach Duy Nguyễn nói trước một phòng người",
 dieu_kien=['Là founder hoặc chủ doanh nghiệp mà uy tín cá nhân ảnh hưởng tới việc khách chọn; nếu là chuyên gia, đã có hoạt động kinh doanh thật và đang xây doanh nghiệp từ chuyên môn',
            'Đang tìm hiểu, chưa cần sẵn sàng cam kết đi sâu',
            'Không mất phí, nhưng có sàng lọc theo đối tượng và hành vi',
            'Vào bằng cách đăng ký danh sách chờ Cộng đồng Next Gen Founder'],
 cho_ai="Founder hoặc chủ doanh nghiệp mà uy tín cá nhân ảnh hưởng tới việc khách chọn, đang tìm hiểu nhân dạng Next Gen Founder nhưng chưa đủ dữ liệu hoặc chưa sẵn sàng cam kết để tham gia sâu; gồm chuyên gia đang xây doanh nghiệp từ chuyên môn.",
 luan_diem="Không ai nên trả tiền cho một chỗ mình chưa biết có hợp hay không. Cộng đồng Mở tồn tại để bạn tự kiểm chứng trước, và để Duy lọc đúng người trước khi mời đi tiếp.",
 ket_qua=["Nội dung chọn lọc theo bốn năng lực, không phải kho tài liệu để tải về cho đầy",
          "Công cụ tự đánh giá để biết mình đang thiếu năng lực nào",
          "Hội thảo và thảo luận mở với người cùng vị trí",
          "Hướng dẫn chọn bước tiếp theo, kể cả khi bước đó không phải một chương trình của Duy"],
 hinh_thuc="Không mất phí, có sàng lọc theo đối tượng và hành vi.",
 khong_gom=["Không mở cửa tự do cho người vào chỉ để săn tài liệu",
            "Không nhận người vào để quảng cáo hoặc chào bán dịch vụ",
            "Không thay thế nhịp đồng hành của Cộng đồng Thành viên"]),

dict(tep="founder-growth-system-lab.html", nhom="Riêng",
 ten="Founder Growth System Lab", ten_vi="Phòng triển khai Hệ thống Tăng trưởng",
 nang_luc="Bước thực hành sau Founder Growth System",
 tom="Xây và chạy thử một luồng công việc thật cùng đội ngũ, có người phụ trách, có dữ liệu và có nhịp rà soát.",
 anh="img/cd-workshop.webp", alt="Coach Duy Nguyễn làm việc cùng một nhóm nhà sáng lập",
 dieu_kien=['Đã học Founder Growth System, đây là bước thực hành tiếp theo',
            'Có quản lý chủ chốt cùng cam kết tham gia từ đầu tới cuối',
            'Đi được nhóm nhỏ trong 8 tới 12 tuần',
            'Mở theo đợt, hỏi qua buổi trao đổi ngắn'],
 cho_ai="Nhà sáng lập đã học Founder Growth System và có quản lý chủ chốt cùng cam kết tham gia.",
 luan_diem="Học xong một hệ thống không có nghĩa là chạy được nó. Phần khó nằm ở lần chạy thật đầu tiên, khi phải chọn người phụ trách, chốt tiêu chuẩn và chịu được việc số liệu ban đầu chưa đẹp.",
 ket_qua=["Một luồng thật được xây và chạy thử, không dừng ở bản vẽ trên giấy",
          "Một người phụ trách luồng đó, có tên và có quyền quyết định",
          "Tài liệu và dữ liệu đủ để đội ngũ tiếp tục khi Duy rút đi",
          "Một nhịp rà soát cố định đã chạy được vài vòng"],
 hinh_thuc="Nhóm nhỏ, từ 8 đến 12 tuần. Đây là bước thực hành chuyên sâu, không phải một cấp cộng đồng mới.",
 khong_gom=["Không nhận nhà sáng lập chưa học Founder Growth System",
            "Không nhận doanh nghiệp mà quản lý chủ chốt không tham gia",
            "Không viết hộ quy trình cho toàn bộ doanh nghiệp"]),
]

# Thứ tự hiện trên trang. Trong mỗi nhóm, xếp từ cửa vào rộng nhất tới phạm vi hẹp nhất.
THU_TU = ["trusted-founder-brand.html", "trusted-sales-team-system.html",
          "founder-growth-system.html", "community-growth-system.html",
          "cong-dong-mo.html", "cong-dong-thanh-vien.html", "diamond-founder-club.html",
          "founder-growth-system-lab.html", "co-van-rieng.html", "giai-phap-doanh-nghiep.html"]
CT = sorted(CT, key=lambda d: THU_TU.index(d["tep"]) if d["tep"] in THU_TU else 99)
