# -*- coding: utf-8 -*-
"""Tám chương trình trong hệ sinh thái Next Gen Founder.
Nguồn: NGF-05 v1.2 và tài liệu The Trusted Creator v1.4. Không tự thêm chương trình mới."""

CT = [

dict(tep="the-trusted-creator.html", nhom="Bốn năng lực",
 ten="The Trusted Creator 30 Days", ten_vi="Người kiến tạo nội dung đáng tin trong 30 ngày",
 nang_luc="Năng lực 01 · Thương hiệu nhà sáng lập được tin cậy",
 tom="Biến những nội dung rời rạc thành một thương hiệu cá nhân được tin và một hệ thống nội dung dẫn đúng người đến gần hơn.",
 anh="img/cd-giang-slide.webp", alt="Coach Duy Nguyễn giảng trước màn chiếu",
 mo_ban=True,
 cho_ai="Nhà sáng lập, chuyên gia và người bán hàng cấp cao đã có chuyên môn, sản phẩm và khách hàng thật, đã bắt đầu xuất hiện nhưng nội dung còn rời rạc.",
 luan_diem="Thương hiệu cá nhân không được xây bằng số lượng bài đăng. Nó được tích luỹ khi đúng người liên tục nhận ra cùng một chuyên môn, cùng một tiêu chuẩn và cùng một cách nhìn qua những bằng chứng thật.",
 ket_qua=["Làm rõ vị thế và lãnh địa chuyên môn, để thị trường nhớ đúng bạn vì một giá trị rõ",
          "Xây kho câu chuyện từ công việc thật, dùng được lâu dài thay vì cạn ý sau vài tuần",
          "Luyện cách diễn đạt qua video và các định dạng phù hợp với con người bạn",
          "Thiết lập nhịp sản xuất một người vận hành được, có AI hỗ trợ phần lặp lại",
          "Tạo một tài sản thu thông tin và bắt đầu đo tín hiệu dẫn tới cuộc trao đổi với đúng người"],
 hinh_thuc="30 ngày, học theo nhóm, có bài tập và phản hồi. Không gian nộp bài và bảng theo dõi chung, bộ mẫu và phiếu tự xem lại, một phiên tổng kết bằng chứng.",
 khai_giang="Khoá đầu tiên khai giảng ngày 28 tháng 9 năm 2026",
 gia=[("Đăng ký sớm", "10 triệu đồng chưa thuế, 10,8 triệu đồng đã gồm thuế giá trị gia tăng 8%", "Từ khi mở bán đến hết ngày 20 tháng 9 năm 2026"),
      ("Tuần cuối", "14 triệu đồng chưa thuế, 15,12 triệu đồng đã gồm thuế giá trị gia tăng 8%", "Từ ngày 21 tháng 9 năm 2026 đến khi đóng đăng ký")],
 gia_ghi="Đây là giá riêng của khoá đầu tiên, thấp hơn vùng giá chuẩn của chương trình, vì khoá này chưa có bằng chứng người học. Từ khoá thứ hai, giá quay về vùng chuẩn.",
 khong_gom=["Không bảo đảm số lượt xem, người theo dõi, khách hàng hoặc doanh thu",
            "Không bảo đảm bạn xây xong một thương hiệu trưởng thành trong 30 ngày",
            "Không thay thế chất lượng sản phẩm và năng lực tư vấn của bạn",
            "Không làm nội dung thay bạn"]),

dict(tep="the-trusted-advisor.html", nhom="Bốn năng lực",
 ten="The Trusted Advisor", ten_vi="Chuyên gia tư vấn được tin cậy",
 nang_luc="Năng lực 02 · Tư vấn có trách nhiệm",
 tom="Nâng chất lượng cuộc tư vấn: khai thác bối cảnh, chẩn đoán, trình bày giải pháp và thống nhất bước tiếp theo mà không gây áp lực.",
 anh="img/cd-workshop.webp", alt="Coach Duy Nguyễn đưa micro cho một học viên",
 cho_ai="Nhà sáng lập, chuyên gia, quản lý và người bán hàng cấp cao cần nâng chất lượng cuộc tư vấn.",
 luan_diem="Uy tín mở cánh cửa. Chất lượng tư vấn và chất lượng giao hàng mới quyết định quan hệ dài hạn. Bán bằng chẩn đoán và sự thật, kể cả khi sự thật là bạn nên nói không.",
 ket_qua=["Khai thác bối cảnh thật của khách thay vì chạy theo câu hỏi bề mặt",
          "Chẩn đoán đúng vấn đề trước khi đưa giải pháp",
          "Đặt câu hỏi dẫn người nghe tự nhìn ra điều họ đang bỏ qua",
          "Trình bày giải pháp theo bối cảnh của khách, không theo danh mục sản phẩm",
          "Xử lý băn khoăn bằng sự thật, và thống nhất bước tiếp theo không gây áp lực"],
 hinh_thuc="4 đến 6 buổi trực tuyến, thực hành tình huống thật và phản hồi trực tiếp.",
 khong_gom=["Không dạy kỹ thuật ép khách chốt nhanh",
            "Không thay thế hiểu biết chuyên môn về ngành của bạn",
            "Không bảo đảm tỷ lệ chốt"]),

dict(tep="founder-growth-system.html", nhom="Bốn năng lực",
 ten="Founder Growth System", ten_vi="Hệ thống tăng trưởng cùng đội ngũ",
 nang_luc="Năng lực 03 · Xây hệ thống cùng đội ngũ",
 tom="Đưa một luồng công việc quan trọng ra khỏi đầu người chủ: có đầu ra, có người chịu trách nhiệm, có dữ liệu và có nhịp rà soát.",
 anh="img/cd-dung-lop.webp", alt="Coach Duy Nguyễn nói trước một phòng người sáng lập",
 cho_ai="Nhà sáng lập đã có sản phẩm, khách hàng và đội ngũ nòng cốt, nhưng tăng trưởng và vận hành còn phụ thuộc vào mình.",
 luan_diem="Kết quả không thể chỉ nằm trong trí nhớ và sự đôn đốc của người chủ. Một hệ thống phải có kết quả rõ, người chịu trách nhiệm, tiêu chuẩn, dữ liệu, bàn giao và nhịp cải tiến.",
 ket_qua=["Một luồng thu hút, tư vấn, bán hàng hoặc vận hành có đầu ra rõ ràng",
          "Một người chịu trách nhiệm cho luồng đó, không phải một phòng ban",
          "Dữ liệu đủ để biết luồng đang khoẻ hay yếu, và một nhịp rà soát cố định",
          "Bản đồ Trust Orbit và hệ sinh thái sản phẩm của riêng doanh nghiệp bạn",
          "Kế hoạch triển khai 90 ngày cùng đội ngũ"],
 hinh_thuc="4 đến 6 buổi trực tuyến, gồm một số phiên chọn lọc cho quản lý chủ chốt.",
 khong_gom=["Không viết hộ quy trình cho toàn bộ doanh nghiệp",
            "Không nhận vai điều hành thay người chủ",
            "Không cam kết một con số doanh thu"]),

dict(tep="community-growth-system.html", nhom="Bốn năng lực",
 ten="Community Growth System", ten_vi="Hệ thống tăng trưởng từ cộng đồng",
 nang_luc="Năng lực 04 · Kiến tạo cộng đồng",
 tom="Thiết kế một cộng đồng mà giá trị được tạo giữa các thành viên với nhau, không chỉ chảy một chiều từ người sáng lập xuống.",
 anh="img/founder-nu-1.webp", alt="Ảnh minh hoạ một nhà sáng lập",
 cho_ai="Nhà sáng lập đã có khách hàng, học viên hoặc người theo dõi, nhưng quan hệ thường kết thúc sau giao dịch và mọi giá trị vẫn phụ thuộc vào mình.",
 luan_diem="Cộng đồng không phải nhóm đăng bài hoặc nơi chào hàng. Giá trị phải được tạo giữa các thành viên qua thực hành, phản hồi, kết nối, giới thiệu và hợp tác có chọn lọc.",
 ket_qua=["Lời hứa cộng đồng rõ ràng và tiêu chuẩn thành viên",
          "Trải nghiệm mười bốn ngày đầu để người mới có thắng nhỏ sớm",
          "Nghi thức và nhịp hoạt động để người ta biết khi nào quay lại",
          "Cơ chế tạo quan hệ, giữ chân, giới thiệu và cơ hội kinh doanh giữa thành viên",
          "Chạy thử một nhịp cộng đồng thật ngay trong chương trình"],
 hinh_thuc="4 đến 6 buổi trực tuyến, kết hợp thiết kế và chạy thử một nhịp cộng đồng thật, gồm một số phiên cho người phụ trách cộng đồng.",
 khong_gom=["Không vận hành cộng đồng thay bạn",
            "Không bảo đảm số thành viên",
            "Không hợp với người chỉ muốn có thêm một nhóm để bán hàng"]),

dict(tep="cong-dong-thanh-vien.html", nhom="Đồng hành",
 ten="Cộng đồng Thành viên Next Gen Founder", ten_vi="Nơi bốn năng lực được luyện cả năm",
 nang_luc="Sản phẩm chủ đạo",
 tom="Không phải một gói xem nội dung không giới hạn. Là môi trường phát triển có lộ trình, có nhịp, có phản hồi và có người đi cùng.",
 anh="img/cd-san-khau.webp", alt="Coach Duy Nguyễn trên sân khấu",
 la_cong_dong=True,
 cho_ai="Nhà sáng lập, chuyên gia và người đang dẫn một đội, muốn luyện đủ bốn năng lực trong công việc thật thay vì học rời từng khoá.",
 luan_diem="Khoá học là lộ trình năng lực bên trong hành trình thành viên, không phải trung tâm của mô hình. Giá trị được đo bằng thay đổi có bằng chứng, không bằng số giờ video đã xem.",
 ket_qua=["Lộ trình bốn năng lực, đi theo điểm nghẽn của bạn chứ không theo thứ tự cứng",
          "Thư viện chương trình và công cụ dùng được trong việc thật",
          "Phiên thực hành và phản hồi trên tình huống của chính bạn",
          "Nhóm đồng hành và kết nối giữa các thành viên",
          "Hồ sơ tiến bộ ghi lại Bước Tăng Trưởng có bằng chứng"],
 hinh_thuc="Thành viên theo năm, có nhịp hoạt động cố định hằng tháng và trải nghiệm mười bốn ngày đầu để bắt đầu đúng.",
 khong_gom=["Không gồm tư vấn riêng không giới hạn",
            "Không gồm quyền tiếp cận Coach Duy bất cứ lúc nào",
            "Không gồm triển khai hệ thống cho doanh nghiệp",
            "Không cam kết doanh thu"]),

dict(tep="diamond-founder-club.html", nhom="Đồng hành",
 ten="Diamond Founder Club", ten_vi="Cộng đồng đồng hành cao cấp, theo lời mời",
 nang_luc="Tầng cao cấp",
 tom="Dành cho nhà sáng lập đã có kết quả, có tinh thần đóng góp và phù hợp văn hoá. Nhận qua xét mời, không mở đăng ký.",
 anh="img/founder-nam-1.webp", alt="Ảnh minh hoạ một nhà sáng lập",
 cho_ai="Nhà sáng lập đúng nhóm khách hàng lõi, đã có kết quả quan sát được, có tinh thần đóng góp cho người đi sau và phù hợp văn hoá.",
 luan_diem="Khả năng chi trả là điều kiện cần, không phải điều kiện đủ. Một cộng đồng cao cấp giữ được chất lượng bằng cách chọn người, không bằng cách chọn giá.",
 ket_qua=["Founder Council, nơi các quyết định lớn được đưa ra bàn cùng người ngang tầm",
          "Bốn lộ trình năng lực ở mức chuyên sâu",
          "Business Clinic cho tình huống thật của doanh nghiệp thành viên",
          "Quyền tham gia chọn lọc cho quản lý chủ chốt",
          "Mạng lưới nhà sáng lập, hoạt động đời sống và cơ chế ghi nhận"],
 hinh_thuc="Xét mời qua hội đồng. Thành viên theo năm.",
 khong_gom=["Không gồm triển khai hệ thống cho doanh nghiệp",
            "Không gồm tư vấn riêng không giới hạn",
            "Không nhận vai làm thuê chức năng",
            "Không cam kết doanh thu",
            "Không gồm quyền tiếp cận Coach Duy bất cứ lúc nào"]),

dict(tep="co-van-rieng.html", nhom="Riêng",
 ten="Founder Private&nbsp;Advisory", ten_vi="Cố vấn riêng cho nhà sáng lập",
 nang_luc="Một kèm một",
 tom="Bốn tháng đi cùng một nhà sáng lập đang đứng trước một quyết định chiến lược đủ lớn. Công suất rất giới hạn.",
 anh="img/cd-chan-dung.webp", alt="Chân dung Coach Duy Nguyễn", anh_tach_nen=True,
 cho_ai="Số ít nhà sáng lập có quyết định chiến lược đủ lớn, và đã sẵn sàng đưa quyết định đó ra bàn với một người ngoài.",
 luan_diem="Cố vấn riêng không phải là gói cao nhất trong một cái thang. Nó là một phạm vi riêng, chỉ hợp khi quyết định đủ lớn để xứng đáng với thời gian của cả hai bên.",
 ket_qua=["Gọi đúng tên quyết định đang phải ra, và điều kiện để ra được quyết định đó",
          "Một bản đồ lựa chọn với cái giá của từng lựa chọn",
          "Nhịp làm việc cố định trong bốn tháng để bám theo tiến độ thật",
          "Tiêu chí để bạn tự đánh giá những quyết định tương tự về sau"],
 hinh_thuc="Cố vấn một kèm một trong bốn tháng. Nhận chọn lọc, không đặt mục tiêu bán số lượng.",
 khong_gom=["Không làm thay phần việc điều hành",
            "Không nhận nếu quyết định chưa đủ lớn để cần cố vấn riêng",
            "Không cam kết doanh thu"]),

dict(tep="giai-phap-doanh-nghiep.html", nhom="Riêng",
 ten="90 Ngày Xây Hệ thống Tăng&nbsp;trưởng", ten_vi="Giải pháp cho doanh nghiệp",
 nang_luc="Hợp đồng doanh nghiệp",
 tom="Chẩn đoán, thiết kế, xây, chạy thử và bàn giao một hệ thống tăng trưởng có người phụ trách, dữ liệu và nhịp điều hành.",
 anh="img/founder-nam-2.webp", alt="Ảnh minh hoạ một nhà sáng lập",
 cho_ai="Doanh nghiệp có nhà sáng lập và quản lý chủ chốt cùng tham gia, có dữ liệu và có vấn đề lặp lại đủ rõ.",
 luan_diem="Chúng tôi không mở rộng giải pháp doanh nghiệp trước khi có bằng chứng, công suất và người chịu trách nhiệm giao hàng. Vì vậy số lượng nhận mỗi đợt rất ít.",
 ket_qua=["Chẩn đoán điểm nghẽn ở mức doanh nghiệp, không chỉ ở mức người chủ",
          "Thiết kế và xây một hệ thống tăng trưởng cho một luồng ưu tiên",
          "Chạy thử trong việc thật, có dữ liệu và tài liệu",
          "Bàn giao cho người phụ trách trong doanh nghiệp, kèm nhịp điều hành"],
 hinh_thuc="90 ngày. Phạm vi có thể gồm Trust Orbit, hệ sinh thái sản phẩm, hệ thống quản lý khách hàng, hội thảo, tư vấn bán hàng, bảng chỉ số và tài liệu vận hành.",
 khong_gom=["Không nằm trong phí Cộng đồng Thành viên hoặc Diamond, đây là hợp đồng riêng",
            "Không bán đại trà, mỗi đợt nhận rất ít doanh nghiệp",
            "Không nhận nếu quản lý chủ chốt không tham gia",
            "Không cam kết doanh thu"]),
]
